"""Add gcs_blob_name to RenderJob model

Revision ID: 990df985f595
Revises: b64ae2e3a9e1
Create Date: 2025-09-30 19:45:14.436783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990df985f595'
down_revision = 'b64ae2e3a9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gcs_blob_name', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('render_job', schema=None) as batch_op:
        batch_op.drop_column('gcs_blob_name')

    # ### end Alembic commands ###
