"""Add Purchase and FreeDownloadUsage models for one-time licensing

Revision ID: f6ea80e3442e
Revises: 990df985f595
Create Date: 2025-10-02 21:35:05.514667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ea80e3442e'
down_revision = '990df985f595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_user_email'))
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
